apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dns-config-webhook-cert
  namespace: default
spec:
  dnsNames:
    - dns-config-webhook.default.svc
    - dns-config-webhook.default.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
  secretName: webhook-certs