apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-config-settings
  namespace: default
data:
  config.yaml: |
    dnsConfig:
      options:
        - name: ndots
          value: "1"
        - name: timeout
          value: "1"