# Update the deployment to use the ServiceAccount
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-config-webhook
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dns-config-webhook
  template:
    metadata:
      labels:
        app: dns-config-webhook
    spec:
      serviceAccountName: dns-config-webhook
      containers:
        - name: webhook
          image: dokfish/k8s-dnsconfig-webhook:0.8
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: dns-config
              mountPath: /etc/webhook/config
              readOnly: true
          env:
            - name: LOG_LEVEL
              value: "2"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 1
            periodSeconds: 2
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: webhook-certs
          secret:
            secretName: webhook-certs
        - name: dns-config
          configMap:
            name: dns-config-settings