apiVersion: v1
kind: Service
metadata:
  name: dns-config-webhook
  namespace: default
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: dns-config-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-config-webhook
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dns-config-webhook
  template:
    metadata:
      labels:
        app: dns-config-webhook
    spec:
      containers:
        - name: webhook
          image: dns-config-webhook:latest
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: webhook-certs